import fs from 'node:fs';

const DATA_CHUNKS=Array.from({length:56},(_,i)=>`data/chunk-${String(i+1).padStart(3,'0')}.csv`);
function trLower(v=''){return String(v).replaceAll('I','ı').replaceAll('İ','i').toLocaleLowerCase('tr-TR')}
function num(v){const s=String(v??'').trim();if(s==='')return null;const matches=s.replace(',','.').match(/\d+(?:\.\d+)?/g);if(!matches)return null;const values=matches.map(Number).filter(Number.isFinite);return values.length?Math.max(...values):null;}
function parseCSV(text){const rows=[];let row=[],field='',q=false;for(let i=0;i<text.length;i++){const c=text[i];if(q){if(c==='"'&&text[i+1]==='"'){field+='"';i++}else if(c==='"')q=false;else field+=c;}else{if(c==='"')q=true;else if(c===','){row.push(field);field=''}else if(c==='\n'){row.push(field);rows.push(row);row=[];field=''}else if(c!=='\r')field+=c;}}if(field.length||row.length){row.push(field);rows.push(row)}const headers=rows.shift().map((h,i)=>i===0?h.replace(/^\uFEFF/,''):h);return rows.filter(r=>r.some(Boolean)).map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]??''])));}
let STUDENT_OVERRIDES={};
const payload=JSON.parse(fs.readFileSync('data/student-overrides.json','utf8'));if(payload?.schools)STUDENT_OVERRIDES={...payload.schools};
function studentInfo(r){const code=String(r.kurum_kodu||'').trim();const csvVals=[num(r.ogrenci_sayisi),num(r.ogrenci_sayilari)].filter(v=>v!==null);const o=Object.prototype.hasOwnProperty.call(STUDENT_OVERRIDES,code)?STUDENT_OVERRIDES[code]:null;const overrideVals=[];if(o){const direct=num(o.value);if(direct!==null)overrideVals.push(direct);if(Array.isArray(o.observed_values)){for(const v of o.observed_values){const n=num(v);if(n!==null)overrideVals.push(n);}}}const vals=[...csvVals,...overrideVals];if(o?.student_count_status==='under_100_manual_review')return {value:null,under100:true};if(!vals.length)return {value:null,under100:false};const value=Math.max(...vals);if(value===0){if(o?.verified)return {value:0,under100:false};return {value:null,under100:false};}return {value,under100:false};}
function schoolLevel(r){const t=(r.okul_turu||'').trim(),tl=trLower(t);if(t==='Anaokulu'||tl.includes('anaokulu')||tl.includes('ana okulu'))return 'Anaokulu';return 'Other';}
function statusFor(r){const t=r.okul_turu||'',tl=trLower(t),si=studentInfo(r),n=si.value,name=trLower(r.okul_adi);const boarding=['yatılı','pansiyonlu','pansiyon'].some(k=>name.includes(k)||tl.includes(k));if(t==='Anaokulu'||tl.includes('anaokulu')||tl.includes('ana okulu')){if(si.under100)return {status:'Hesaplandı',norm:boarding?1:0};if(n===null)return boarding?{status:'Kısmi hesap',norm:1}:{status:'Ek veri gerekli',norm:null};return {status:'Hesaplandı',norm:Math.max((n>=150?1:0)+Math.floor(n/500),boarding?1:0)};}return {status:'Other',norm:0};}
const text=DATA_CHUNKS.map(f=>fs.readFileSync(f,'utf8')).join('\n');
const allRows=parseCSV(text).map(r=>({...r,kademe:schoolLevel(r),...statusFor(r)}));
const ana=allRows.filter(r=>r.kademe==='Anaokulu');
const flagged=ana.filter(r=>r.norm===null||r.status!=='Hesaplandı');
const report={all_rows:allRows.length,anaokulu_total:ana.length,anaokulu_flagged:flagged.length,flagged:flagged.map(r=>({kurum_kodu:r.kurum_kodu,okul_adi:r.okul_adi,il:r.il,ilce:r.ilce,okul_turu:r.okul_turu,status:r.status,ogrenci_sayisi:r.ogrenci_sayisi,ogrenci_sayilari:r.ogrenci_sayilari,override:STUDENT_OVERRIDES[String(r.kurum_kodu||'').trim()]??null}))};
fs.writeFileSync('data/preschool-js-audit.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));
